[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
itertools = "0.12.1"
parse-display = "0.9.0"
partition = "0.1.2"
tailcall = "1.0.1"
unindent = "0.2.3"
derive-new = "0.6.0"
derive_more = "0.99.17"
bstr = "1.9.1"
num = "0.4.3"